# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from parse import PTN

def parse(name: str, standardise: bool, coherent_types: bool) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import re