# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from _version import version
from typing import Any
import sys

__version__ = 'unknown'
__all__ = ['easter', 'parser', 'relativedelta', 'rrule', 'tz', 'utils', 'zoneinfo']
def __getattr__(name: Any) -> Any:
    ...

def __dir__() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import importlib
import datetime
import functools
import warnings
import __future__
import re
import string
import time
import calendar
import io
import six
import decimal
import operator
import math
import heapq
import itertools
import six.moves
import fractions
import weakref
import collections
import collections.OrderedDict
import struct
import bisect
import ntpath
import dateutil.zoneinfo.get_zonefile_instance
import contextlib
import ctypes
import ctypes.wintypes
import json
import tarfile
import pkgutil
import dateutil.tz.tzfile
import logging
import tempfile
import shutil
import subprocess
import dateutil.zoneinfo.METADATA_FN
import dateutil.zoneinfo.ZONEFILENAME