# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from importlib import metadata
from paramiko.agent import Agent, AgentKey
from paramiko.auth_handler import AuthHandler
from paramiko.auth_strategy import AuthFailure, AuthResult, AuthSource, AuthStrategy, InMemoryPrivateKey, NoneAuth, OnDiskPrivateKey, Password, PrivateKey, SourceResult
from paramiko.channel import Channel, ChannelFile, ChannelStderrFile, ChannelStdinFile
from paramiko.client import AutoAddPolicy, MissingHostKeyPolicy, RejectPolicy, SSHClient, WarningPolicy
from paramiko.common import AUTH_FAILED, AUTH_PARTIALLY_SUCCESSFUL, AUTH_SUCCESSFUL, OPEN_FAILED_ADMINISTRATIVELY_PROHIBITED, OPEN_FAILED_CONNECT_FAILED, OPEN_FAILED_RESOURCE_SHORTAGE, OPEN_FAILED_UNKNOWN_CHANNEL_TYPE, OPEN_SUCCEEDED, io_sleep
from paramiko.config import SSHConfig, SSHConfigDict
from paramiko.ecdsakey import ECDSAKey
from paramiko.ed25519key import Ed25519Key
from paramiko.file import BufferedFile
from paramiko.hostkeys import HostKeys
from paramiko.message import Message
from paramiko.packet import Packetizer
from paramiko.pkey import PKey, PublicBlob, UnknownKeyType
from paramiko.proxy import ProxyCommand
from paramiko.rsakey import RSAKey
from paramiko.server import InteractiveQuery, ServerInterface, SubsystemHandler
from paramiko.sftp import BaseSFTP, SFTPError, SFTP_BAD_MESSAGE, SFTP_CONNECTION_LOST, SFTP_EOF, SFTP_FAILURE, SFTP_NO_CONNECTION, SFTP_NO_SUCH_FILE, SFTP_OK, SFTP_OP_UNSUPPORTED, SFTP_PERMISSION_DENIED
from paramiko.sftp_attr import SFTPAttributes
from paramiko.sftp_client import SFTP, SFTPClient
from paramiko.sftp_file import SFTPFile
from paramiko.sftp_handle import SFTPHandle
from paramiko.sftp_server import SFTPServer
from paramiko.sftp_si import SFTPServerInterface
from paramiko.ssh_exception import AuthenticationException, BadAuthenticationType, BadHostKeyException, ChannelException, ConfigParseError, CouldNotCanonicalize, IncompatiblePeer, MessageOrderError, PasswordRequiredException, ProxyCommandFailure, SSHException
from paramiko.transport import SecurityOptions, ServiceRequestingTransport, Transport

key_classes = [RSAKey, Ed25519Key, ECDSAKey]
__author__ = 'Jeff Forcier <jeff@bitprophet.org>'
__license__ = 'GNU Lesser General Public License (LGPL)'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import importlib
import importlib.metadata
import builtins
import ctypes
import ctypes.wintypes
import socket
import stat
import struct
import sys
import tempfile
import threading
import time
import logging
import logging.DEBUG
import select
import fcntl
import weakref
import collections
import collections.namedtuple
import array
import binascii
import functools
import getpass
import inspect
import warnings
import errno
import ntpath
import zlib
import fnmatch
import re
import shlex
import hashlib
import io
import invoke
import typing
import cryptography
import cryptography.exceptions
import cryptography.hazmat
import cryptography.hazmat.backends
import cryptography.hazmat.backends.default_backend
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.hashes
import cryptography.hazmat.primitives.serialization
import cryptography.hazmat.primitives.asymmetric
import cryptography.hazmat.primitives.asymmetric.ec
import cryptography.hazmat.primitives.asymmetric.utils
import bcrypt
import nacl
import nacl.signing
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.Cipher
import base64
import collections.abc
import hmac
import cryptography.hazmat.primitives.constant_time
import cryptography.hazmat.primitives.asymmetric.x25519
import pathlib
import cryptography.hazmat.primitives.padding
import cryptography.hazmat.primitives.asymmetric.ed25519
import cryptography.hazmat.primitives.asymmetric.rsa
import cryptography.hazmat.primitives.ciphers.algorithms
import cryptography.hazmat.primitives.ciphers.modes
import cryptography.hazmat.decrepit
import cryptography.hazmat.decrepit.ciphers
import cryptography.hazmat.decrepit.ciphers.algorithms
import paramiko.ECDSAKey
import paramiko.Ed25519Key
import paramiko.RSAKey
import paramiko.key_classes
import signal
import subprocess
import cryptography.hazmat.primitives.asymmetric.padding
import collections.deque
import cryptography.hazmat.primitives.ciphers.aead
import atexit
import traceback
import platform
import _thread