# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from . import errors
from enums import ICMP_DEFAULT_CODE, IcmpTimeExceededCode, IcmpV4DestinationUnreachableCode, IcmpV4Type, IcmpV6DestinationUnreachableCode, IcmpV6Type
from typing import Any
import errno
import functools
import ipaddress
import logging
import os
import platform
import select
import socket
import struct
import threading
import time
import zlib

__version__ = '5.1.5'
DEBUG = False
EXCEPTIONS = False
LOGGER = None
IPV4_HEADER_FORMAT = '!BBHHHBBHII'
IPV6_HEADER_FORMAT = '!IHBB16s16s'
ICMP_HEADER_FORMAT = '!BBHHH'
ICMP_TIME_FORMAT = '!d'
ICMPV6_PSEUDO_HEADER_FORMAT = '!16s16sIBBBB'
SOCKET_SO_BINDTODEVICE = 25
def _debug() -> None:
    ...

def _raise(err: Exception) -> None:
    ...

def _func_logger(func: Any) -> Any:
    ...

def is_ipv4(sock: socket.socket) -> bool:
    ...

def checksum(source: bytes) -> int:
    ...

def read_icmp_header(raw: bytes) -> dict:
    ...

def read_ipv4_header(raw: bytes) -> dict:
    ...

def read_ipv6_header(raw: bytes) -> dict:
    ...

def send_one_ping(sock: socket.socket, dest_addr: str, icmp_id: int, seq: int, size: int) -> None:
    ...

def receive_one_ping(sock: socket.socket, icmp_id: int, seq: int, timeout: int) -> Any:
    ...

def ping(dest_addr: str, timeout: int, unit: str, src_addr: str, ttl: Any, seq: int, size: int, interface: str, version: Any) -> Any:
    ...

def verbose_ping(dest_addr: str, count: int, interval: float) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import socket
import struct
import select
import time
import platform
import zlib
import threading
import logging
import functools
import errno
import ipaddress
import argparse
import enum