# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __version__ import __author__, __author_email__, __copyright__, __description__, __license__, __title__, __url__, __version__
from inputimeout import TimeoutOccurred, inputimeout


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import msvcrt
import selectors
import termios
import time