# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from _monitor import TMonitor, TqdmSynchronisationWarning
from _tqdm_pandas import tqdm_pandas
from cli import main
from gui import tqdm, trange
from std import TqdmDeprecationWarning, TqdmExperimentalWarning, TqdmKeyError, TqdmMonitorWarning, TqdmTypeError, TqdmWarning, tqdm, trange
from typing import Any
from version import __version__

__all__ = ['tqdm', 'tqdm_gui', 'trange', 'tgrange', 'tqdm_pandas', 'tqdm_notebook', 'tnrange', 'main', 'TMonitor', 'TqdmTypeError', 'TqdmKeyError', 'TqdmWarning', 'TqdmDeprecationWarning', 'TqdmExperimentalWarning', 'TqdmMonitorWarning', 'TqdmSynchronisationWarning', '__version__']
def tqdm_notebook() -> Any:
    ...

def tnrange() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import warnings
import atexit
import threading
import time
import sys
import tqdm.TqdmDeprecationWarning
import asyncio
import logging
import re
import ast
import textwrap
import importlib_resources
import importlib
import importlib.resources
import pathlib
import numpy
import contextlib
import operator
import concurrent
import concurrent.futures
import concurrent.futures.ThreadPoolExecutor
import concurrent.futures.ProcessPoolExecutor
import requests
import requests.Session
import requests.utils
import itertools
import math
import typing
import slack_sdk
import collections
import collections.deque
import functools
import dask
import dask.callbacks
import matplotlib
import matplotlib.pyplot
import copy
import keras
import tensorflow
import html
import html.escape
import weakref
import ipywidgets
import IPython
import IPython.html
import IPython.html.widgets
import IPython.display
import rich
import rich.progress
import collections.OrderedDict
import collections.defaultdict
import datetime
import numbers
import multiprocessing
import multiprocessing.RLock
import pandas
import pandas.core
import pandas.core.frame
import pandas.core.series
import pandas.core.window
import pandas.core.window.rolling
import pandas.core.window.expanding
import pandas.core.groupby
import pandas.core.groupby.generic
import pandas.core.groupby.groupby
import pandas.core.common
import tkinter
import tkinter.ttk
import inspect
import unicodedata
import colorama
import envwrap
import importlib.metadata