# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from tomli_w._writer import dump, dumps

__all__ = ('dumps', 'dump')
__version__ = '1.2.0'

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import __future__
import collections
import collections.abc
import datetime
import types
import decimal