# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from toml import decoder, encoder

__version__ = '0.10.2'
_spec_ = '0.5.0'
load = decoder.load
loads = decoder.loads
TomlDecoder = decoder.TomlDecoder
TomlDecodeError = decoder.TomlDecodeError
TomlPreserveCommentDecoder = decoder.TomlPreserveCommentDecoder
dump = encoder.dump
dumps = encoder.dumps
TomlEncoder = encoder.TomlEncoder
TomlArraySeparatorEncoder = encoder.TomlArraySeparatorEncoder
TomlPreserveInlineDictEncoder = encoder.TomlPreserveInlineDictEncoder
TomlNumpyEncoder = encoder.TomlNumpyEncoder
TomlPreserveCommentEncoder = encoder.TomlPreserveCommentEncoder
TomlPathlibEncoder = encoder.TomlPathlibEncoder

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import datetime
import io
import re
import sys
import pathlib
import ntpath
import warnings
import decimal
import numpy
import collections
import collections.OrderedDict
import toml.TomlEncoder
import toml.TomlDecoder