# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from cyaml import *
from dumper import *
from error import *
from events import *
from loader import *
from nodes import *
from tokens import *
from typing import Any
import io

__version__ = '6.0.3'
__with_libyaml__ = True
__with_libyaml__ = False
def warnings(settings: Any) -> Any:
    ...

def scan(stream: Any, Loader: Any) -> Any:
    ...

def parse(stream: Any, Loader: Any) -> Any:
    ...

def compose(stream: Any, Loader: Any) -> Any:
    ...

def compose_all(stream: Any, Loader: Any) -> Any:
    ...

def load(stream: Any, Loader: Any) -> Any:
    ...

def load_all(stream: Any, Loader: Any) -> Any:
    ...

def full_load(stream: Any) -> Any:
    ...

def full_load_all(stream: Any) -> Any:
    ...

def safe_load(stream: Any) -> Any:
    ...

def safe_load_all(stream: Any) -> Any:
    ...

def unsafe_load(stream: Any) -> Any:
    ...

def unsafe_load_all(stream: Any) -> Any:
    ...

def emit(events: Any, stream: Any, Dumper: Any, canonical: Any, indent: Any, width: Any, allow_unicode: Any, line_break: Any) -> Any:
    ...

def serialize_all(nodes: Any, stream: Any, Dumper: Any, canonical: Any, indent: Any, width: Any, allow_unicode: Any, line_break: Any, encoding: Any, explicit_start: Any, explicit_end: Any, version: Any, tags: Any) -> Any:
    ...

def serialize(node: Any, stream: Any, Dumper: Any) -> Any:
    ...

def dump_all(documents: Any, stream: Any, Dumper: Any, default_style: Any, default_flow_style: Any, canonical: Any, indent: Any, width: Any, allow_unicode: Any, line_break: Any, encoding: Any, explicit_start: Any, explicit_end: Any, version: Any, tags: Any, sort_keys: Any) -> Any:
    ...

def dump(data: Any, stream: Any, Dumper: Any) -> Any:
    ...

def safe_dump_all(documents: Any, stream: Any) -> Any:
    ...

def safe_dump(data: Any, stream: Any) -> Any:
    ...

def add_implicit_resolver(tag: Any, regexp: Any, first: Any, Loader: Any, Dumper: Any) -> Any:
    ...

def add_path_resolver(tag: Any, path: Any, kind: Any, Loader: Any, Dumper: Any) -> Any:
    ...

def add_constructor(tag: Any, constructor: Any, Loader: Any) -> Any:
    ...

def add_multi_constructor(tag_prefix: Any, multi_constructor: Any, Loader: Any) -> Any:
    ...

def add_representer(data_type: Any, representer: Any, Dumper: Any) -> Any:
    ...

def add_multi_representer(data_type: Any, multi_representer: Any, Dumper: Any) -> Any:
    ...

class YAMLObjectMetaclass(type):
    def __init__(cls: cls, name: Any, bases: Any, kwds: Any) -> None: ...

class YAMLObject:
    @classmethod
    def from_yaml(cls, loader: Any, node: Any) -> Any: ...
    @classmethod
    def to_yaml(cls, dumper: Any, data: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import io
import collections
import collections.abc
import datetime
import base64
import binascii
import re
import sys
import types
import yaml._yaml
import codecs
import copyreg